// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soakbndaquvrvxsdless.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYWtibmRhcXV2cnZ4c2RsZXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTYwNDQsImV4cCI6MjA2Mzc5MjA0NH0.k4XI1_Ru06_EuTUeLDJWSfgBGIoS2-gcZXm52scpyzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);